package flags

import (
	"os"
	"path/filepath"
	"rpc/pkg/utils"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestPrintMaintenanceUsage(t *testing.T) {
	executable := filepath.Base(os.Args[0])
	args := []string{executable}
	flags := NewFlags(args)
	output := flags.printMaintenanceUsage()
	usage := "\nRemote Provisioning Client (RPC) - used for activation, deactivation, maintenance and status of AMT\n\n"
	usage = usage + "Usage: " + executable + " maintenance COMMAND [OPTIONS]\n\n"
	usage = usage + "Supported Maintenance Commands:\n"
	usage = usage + "  changepassword Change the AMT password. A random password is generated by default. Specify -static to set manually. AMT password is required\n"
	usage = usage + "                 Example: " + executable + " maintenance changepassword -u wss://server/activate\n"
	usage = usage + "  syncclock      Sync the host OS clock to AMT. AMT password is required\n"
	usage = usage + "                 Example: " + executable + " maintenance syncclock -u wss://server/activate\n"
	usage = usage + "  synchostname   Sync the hostname of the client to AMT. AMT password is required\n"
	usage = usage + "                 Example: " + executable + " maintenance synchostname -u wss://server/activate\n"
	usage = usage + "  syncip         Sync the IP configuration of the host OS to AMT Network Settings. AMT password is required\n"
	usage = usage + "                 Example: " + executable + " maintenance syncip -staticip 192.168.1.7 -netmask 255.255.255.0 -gateway 192.168.1.1 -primarydns 8.8.8.8 -secondarydns 4.4.4.4 -u wss://server/activate\n"
	usage = usage + "                 If a static ip is not specified, the ip address and netmask of the host OS is used\n"
	usage = usage + "\nRun '" + executable + " maintenance COMMAND -h' for more information on a command.\n"
	assert.Equal(t, usage, output)
}

func TestParseFlagsMaintenance(t *testing.T) {
	argUrl := "-u wss://localhost"
	argCurPw := "-password " + trickyPassword
	argSyncClock := "syncclock"
	argSyncHostname := "synchostname"
	argSyncIp := "syncip"
	argChangePw := "changepassword"
	newPassword := trickyPassword + "123"
	cmdBase := "./rpc maintenance"

	ipCfgNoParams := IPConfiguration{
		IpAddress: "192.168.1.1",
		Netmask:   "255.255.255.0",
	}
	ipCfgWithParams := IPConfiguration{
		IpAddress:    "10.20.30.40",
		Netmask:      "255.0.0.0",
		Gateway:      "10.0.0.0",
		PrimaryDns:   "8.8.8.8",
		SecondaryDns: "4.4.4.4",
	}
	ipCfgWithLookup := IPConfiguration{
		IpAddress:    ipCfgNoParams.IpAddress,
		Netmask:      ipCfgNoParams.Netmask,
		Gateway:      "10.0.0.0",
		PrimaryDns:   "1.2.3.4",
		SecondaryDns: "5.6.7.8",
	}
	tests := map[string]struct {
		cmdLine      string
		wantResult   int
		wantRpsCmd   string
		wantIPConfig IPConfiguration
		userInput    string
	}{
		"should fail with usage - no additional arguments": {
			cmdLine:    cmdBase,
			wantResult: utils.IncorrectCommandLineParameters,
			wantRpsCmd: "",
		},
		"should fail with usage - unhandled task": {
			cmdLine:    cmdBase + " someothertask",
			wantResult: utils.IncorrectCommandLineParameters,
			wantRpsCmd: "",
		},
		"should fail - required websocket URL": {
			cmdLine:    cmdBase + " " + argSyncClock,
			wantResult: utils.MissingOrIncorrectURL,
		},
		"should fail - required amt password": {
			cmdLine:    cmdBase + " " + argSyncClock + " " + argUrl,
			wantResult: utils.MissingOrIncorrectPassword,
			wantRpsCmd: "",
		},
		"should pass - syncclock": {
			cmdLine:    cmdBase + " " + argSyncClock + " " + argUrl + " " + argCurPw,
			wantResult: utils.Success,
			// translate arg from clock -> time
			wantRpsCmd: "maintenance -" + argCurPw + " --synctime",
		},
		"should fail - syncclock bad param": {
			cmdLine:    cmdBase + " " + argSyncClock + " -nope " + argUrl + " " + argCurPw,
			wantResult: utils.IncorrectCommandLineParameters,
			wantRpsCmd: "",
		},
		"should pass - synchostname no params": {
			cmdLine:    cmdBase + " " + argSyncHostname + " " + argUrl + " " + argCurPw,
			wantResult: utils.Success,
			wantRpsCmd: "maintenance -" + argCurPw + " --" + argSyncHostname,
		},
		"should pass - task force flag": {
			cmdLine:    cmdBase + " " + argSyncHostname + " -f " + argUrl + " " + argCurPw,
			wantResult: utils.Success,
			wantRpsCmd: "maintenance -" + argCurPw + " --" + argSyncHostname + " -f",
		},
		"should fail - synchostname bad param": {
			cmdLine:    cmdBase + " " + argSyncHostname + " -nope " + argUrl + " " + argCurPw,
			wantResult: utils.IncorrectCommandLineParameters,
			wantRpsCmd: "",
		},
		"should pass - syncip no params": {
			cmdLine:      cmdBase + " " + argSyncIp + " " + argUrl + " " + argCurPw,
			wantResult:   utils.Success,
			wantRpsCmd:   "maintenance -" + argCurPw + " --" + argSyncIp,
			wantIPConfig: ipCfgNoParams,
		},
		"should pass - syncip with params": {
			cmdLine: cmdBase + " " +
				argSyncIp +
				" -staticip " + ipCfgWithParams.IpAddress +
				" -netmask " + ipCfgWithParams.Netmask +
				" -gateway " + ipCfgWithParams.Gateway +
				" -primarydns " + ipCfgWithParams.PrimaryDns +
				" -secondarydns " + ipCfgWithParams.SecondaryDns +
				" " + argUrl + " " + argCurPw,
			wantResult:   utils.Success,
			wantRpsCmd:   "maintenance -" + argCurPw + " --" + argSyncIp,
			wantIPConfig: ipCfgWithParams,
		},
		"should pass - syncip with lookup": {
			cmdLine: cmdBase + " " +
				argSyncIp +
				" -gateway " + ipCfgWithLookup.Gateway +
				" -primarydns " + ipCfgWithLookup.PrimaryDns +
				" -secondarydns " + ipCfgWithLookup.SecondaryDns +
				" " + argUrl + " " + argCurPw,
			wantResult:   utils.Success,
			wantRpsCmd:   "maintenance -" + argCurPw + " --" + argSyncIp,
			wantIPConfig: ipCfgWithLookup,
		},
		"should fail - syncip bad param": {
			cmdLine:    cmdBase + " " + argSyncIp + " -nope " + argUrl + " " + argCurPw,
			wantResult: utils.IncorrectCommandLineParameters,
			wantRpsCmd: "",
		},
		"should fail - syncip MissingOrIncorrectNetworkMask": {
			cmdLine:    cmdBase + " " + argSyncIp + " -netmask 322.299.0.0 " + argUrl + " " + argCurPw,
			wantResult: utils.MissingOrIncorrectNetworkMask,
			wantRpsCmd: "",
		},
		"should fail - syncip MissingOrIncorrectStaticIP": {
			cmdLine:    cmdBase + " " + argSyncIp + " -staticip 322.299.0.0 " + argUrl + " " + argCurPw,
			wantResult: utils.MissingOrIncorrectStaticIP,
			wantRpsCmd: "",
		},
		"should fail - syncip MissingOrIncorrectGateway": {
			cmdLine:    cmdBase + " " + argSyncIp + " -gateway 322.299.0.0 " + argUrl + " " + argCurPw,
			wantResult: utils.MissingOrIncorrectGateway,
			wantRpsCmd: "",
		},
		"should fail - syncip MissingOrIncorrectPrimaryDNS": {
			cmdLine:    cmdBase + " " + argSyncIp + " -primarydns 322.299.0.0 " + argUrl + " " + argCurPw,
			wantResult: utils.MissingOrIncorrectPrimaryDNS,
			wantRpsCmd: "",
		},
		"should fail - syncip MissingOrIncorrectSecondaryDNS": {
			cmdLine:    cmdBase + " " + argSyncIp + " -secondarydns 322.299.0.0 " + argUrl + " " + argCurPw,
			wantResult: utils.MissingOrIncorrectSecondaryDNS,
			wantRpsCmd: "",
		},
		"should pass - changepassword to random value": {
			cmdLine:    cmdBase + " " + argChangePw + " " + argUrl + " " + argCurPw,
			wantResult: utils.Success,
			wantRpsCmd: "maintenance -" + argCurPw + " --" + argChangePw + " ",
		},
		"should pass - changepassword using static value": {
			cmdLine:    cmdBase + " " + argChangePw + " -static " + newPassword + " " + argUrl + " " + argCurPw,
			wantResult: utils.Success,
			wantRpsCmd: "maintenance -" + argCurPw + " --" + argChangePw + " " + newPassword,
		},
		"should pass - changepassword static value before other flags": {
			cmdLine:    cmdBase + " " + argChangePw + " -static " + newPassword + " " + argUrl + " " + argCurPw,
			wantResult: utils.Success,
			wantRpsCmd: "maintenance -" + argCurPw + " --" + argChangePw + " " + newPassword,
		},
		"should pass - changepassword static value after all flags": {
			cmdLine:    cmdBase + " " + argChangePw + " " + argUrl + " " + argCurPw + " -static " + newPassword,
			wantResult: utils.Success,
			wantRpsCmd: "maintenance -" + argCurPw + " --" + argChangePw + " " + newPassword,
		},
		"should fail - changepassword bad param": {
			cmdLine:    cmdBase + " " + argChangePw + " -nope " + argUrl + " " + argCurPw,
			wantResult: utils.IncorrectCommandLineParameters,
			wantRpsCmd: "",
		},
		"should pass - password user input": {
			cmdLine:    cmdBase + " " + argSyncClock + " " + argUrl,
			wantResult: utils.Success,
			wantRpsCmd: "maintenance -" + argCurPw + " --synctime",
			userInput:  trickyPassword,
		},
	}

	for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
			args := strings.Fields(tc.cmdLine)
			if tc.userInput != "" {
				defer userInput(t, tc.userInput)()
			}
			flags := NewFlags(args)
			flags.amtCommand.PTHI = MockPTHICommands{}
			flags.netEnumerator = testNetEnumerator
			gotCommand, keepGoing, gotResult := flags.ParseFlags()
			if gotResult == utils.Success {
				assert.Equal(t, keepGoing, true)
			} else {
				assert.Equal(t, keepGoing, false)
			}
			assert.Equal(t, tc.wantResult, gotResult)
			assert.Equal(t, "maintenance", gotCommand)
			assert.Equal(t, tc.wantRpsCmd, flags.Command)
			assert.Equal(t, tc.wantIPConfig, flags.IpConfiguration)
		})
	}
}
